from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, model_validator


class AgentConfig(BaseModel):
    """Configuration for a single LLM agent."""

    name: str
    instruction: str
    model: str | None = None
    output_key: str
    tools: list[str] = []


class PipelineNodeConfig(BaseModel):
    """A node in the pipeline tree."""

    type: Literal["agent", "sequential", "parallel", "loop"]

    # For type="agent": reference to an agent config by name.
    agent_name: str | None = None

    # For type="sequential" / "parallel" / "loop": ordered child nodes.
    children: list[PipelineNodeConfig] = []

    # For type="loop": max iterations before forced exit.
    max_iterations: int | None = None


class PipelineConfig(BaseModel):
    """Complete pipeline configuration generated by the meta-agent."""

    agents: list[AgentConfig]
    pipeline: PipelineNodeConfig

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    @model_validator(mode="after")
    def _validate_config(self) -> PipelineConfig:
        agent_names = {a.name for a in self.agents}
        output_keys = [a.output_key for a in self.agents]

        # Unique agent names
        if len(agent_names) != len(self.agents):
            seen: set[str] = set()
            for a in self.agents:
                if a.name in seen:
                    raise ValueError(f"Duplicate agent name: '{a.name}'")
                seen.add(a.name)

        # Unique output keys
        if len(set(output_keys)) != len(output_keys):
            seen_keys: set[str] = set()
            for a in self.agents:
                if a.output_key in seen_keys:
                    raise ValueError(f"Duplicate output_key: '{a.output_key}'")
                seen_keys.add(a.output_key)

        # Every agent_name referenced in the tree must exist
        self._validate_node_refs(self.pipeline, agent_names)

        return self

    def _validate_node_refs(
        self, node: PipelineNodeConfig, agent_names: set[str]
    ) -> None:
        if node.type == "agent":
            if node.agent_name is None:
                raise ValueError("Node of type 'agent' must have an agent_name")
            if node.agent_name not in agent_names:
                raise ValueError(
                    f"Pipeline references unknown agent '{node.agent_name}'. "
                    f"Available: {sorted(agent_names)}"
                )
        else:
            if not node.children:
                raise ValueError(
                    f"Node of type '{node.type}' must have at least one child"
                )
            for child in node.children:
                self._validate_node_refs(child, agent_names)
