from __future__ import annotations

import re
from typing import Any, Literal

from pydantic import BaseModel, model_validator

from fedotmas._settings import validate_model_name
from fedotmas.common.logging import get_logger
from fedotmas.maw._validators import (
    auto_fill_agent_name,
    validate_node_refs,
    warn_terminal_parallel,
    warn_unused_agents,
)

_log = get_logger("fedotmas.maw.models")

_STATE_VAR_RE = re.compile(r"\{(\w+)\}")
_ANGLE_VAR_RE = re.compile(r"<(\w+)>")


def _replace_in_tree(
    node: MAWStepConfig, name: str, replacement: MAWStepConfig
) -> MAWStepConfig:
    if node.type == "agent":
        return replacement if node.agent_name == name else node
    new_children = [_replace_in_tree(c, name, replacement) for c in node.children]
    return node.model_copy(update={"children": new_children})


def _rename_in_tree(node: MAWStepConfig, old: str, new: str) -> MAWStepConfig:
    if node.type == "agent":
        if node.agent_name == old:
            return node.model_copy(update={"agent_name": new})
        return node
    new_children = [_rename_in_tree(c, old, new) for c in node.children]
    return node.model_copy(update={"children": new_children})


def _insert_after_in_tree(
    node: MAWStepConfig, name: str, new_node: MAWStepConfig
) -> MAWStepConfig:
    if node.type == "agent":
        return node
    new_children: list[MAWStepConfig] = []
    for child in node.children:
        if child.type == "agent" and child.agent_name == name:
            new_children.append(child)
            new_children.append(new_node)
        else:
            new_children.append(_insert_after_in_tree(child, name, new_node))
    return node.model_copy(update={"children": new_children})


def _remove_from_tree(node: MAWStepConfig, name: str) -> MAWStepConfig | None:
    if node.type == "agent":
        return None if node.agent_name == name else node
    new_children: list[MAWStepConfig] = []
    for child in node.children:
        result = _remove_from_tree(child, name)
        if result is not None:
            new_children.append(result)
    if not new_children:
        return None
    if len(new_children) == 1 and node.type in ("sequential", "parallel"):
        return new_children[0]
    return node.model_copy(update={"children": new_children})


def _has_agent_ref(node: MAWStepConfig, name: str) -> bool:
    if node.type == "agent":
        return node.agent_name == name
    return any(_has_agent_ref(c, name) for c in node.children)


class AgentPoolEntry(BaseModel):
    """A single agent definition for stage-1 pool generation.

    Unlike ``MAWAgentConfig``, this does **not** carry ``output_key`` — wiring
    is a stage-2 concern.
    """

    name: str
    instruction: str
    model: str | None = None
    tools: list[str] = []


class AgentPoolConfig(BaseModel):
    """Agent pool produced by stage-1 of two-stage generation."""

    agents: list[AgentPoolEntry]

    @model_validator(mode="after")
    def _unique_names(self) -> AgentPoolConfig:
        seen: set[str] = set()
        for a in self.agents:
            if a.name in seen:
                raise ValueError(f"Duplicate agent name in pool: '{a.name}'")
            seen.add(a.name)
        return self


class MAWAgentConfig(BaseModel):
    """Configuration for a single LLM agent."""

    name: str
    instruction: str
    model: str | None = None
    output_key: str
    tools: list[str] = []

    @model_validator(mode="after")
    def _normalize_fields(self) -> MAWAgentConfig:
        validate_model_name(self.model)

        # Normalize instruction: <var> → {var} → {var?}
        instr = _ANGLE_VAR_RE.sub(r"{\1}", self.instruction)
        self.instruction = _STATE_VAR_RE.sub(r"{\1?}", instr)
        return self


class MAWStepConfig(BaseModel):
    """A node in the pipeline tree."""

    type: Literal["agent", "sequential", "parallel", "loop"] = "agent"

    # For type="agent": reference to an agent config by name.
    agent_name: str | None = None

    # For type="sequential" / "parallel" / "loop": ordered child nodes.
    children: list[MAWStepConfig] = []

    # For type="loop": max iterations before forced exit.
    max_iterations: int | None = None

    @model_validator(mode="before")
    @classmethod
    def _infer_type(cls, data: Any) -> Any:
        """Auto-fill missing ``type`` based on other fields present."""
        if not isinstance(data, dict):
            return data
        if "agent_name" in data and data.get("children"):
            raise ValueError("Cannot specify both 'agent_name' and 'children'")
        if "type" not in data:
            data = dict(data)  # avoid mutating the original
            if "agent_name" in data:
                data["type"] = "agent"
            elif "children" in data:
                data["type"] = "sequential"
        return data


class MAWConfig(BaseModel):
    """Complete pipeline configuration generated by the meta-agent."""

    agents: list[MAWAgentConfig]
    pipeline: MAWStepConfig

    def __str__(self) -> str:
        agents_map = {a.name: a.output_key for a in self.agents}
        pipeline_str = self._format_step(self.pipeline, agents_map)
        lines = [f"Pipeline: {pipeline_str}", "Agents:"]
        for a in self.agents:
            tools = f"  tools: {a.tools}" if a.tools else ""
            lines.append(f"  {a.name:<20} (output: {a.output_key}){tools}")
        return "\n".join(lines)

    def _format_step(self, step: MAWStepConfig, agents_map: dict[str, str]) -> str:
        if step.type == "agent":
            return step.agent_name or "?"
        parts = [self._format_step(c, agents_map) for c in step.children]
        if step.type == "parallel":
            inner = ", ".join(parts)
            return f"[{inner}]"
        if step.type == "loop":
            suffix = f" x{step.max_iterations}" if step.max_iterations else ""
            inner = " \u2192 ".join(parts)
            return f"\u21bb({inner}){suffix}"
        return " \u2192 ".join(parts)

    def replace_agent(self, name: str, agent: MAWAgentConfig) -> MAWConfig:
        if not _has_agent_ref(self.pipeline, name):
            raise ValueError(f"Agent '{name}' not found in pipeline")
        new_agents = [agent if a.name == name else a for a in self.agents]
        if name != agent.name:
            new_pipeline = _rename_in_tree(self.pipeline, name, agent.name)
        else:
            new_pipeline = self.pipeline
        return MAWConfig(agents=new_agents, pipeline=new_pipeline)

    def replace_step(
        self,
        name: str,
        *,
        step: MAWStepConfig,
        agents: list[MAWAgentConfig],
    ) -> MAWConfig:
        if not _has_agent_ref(self.pipeline, name):
            raise ValueError(f"Agent '{name}' not found in pipeline")
        new_pipeline = _replace_in_tree(self.pipeline, name, step)
        new_agents = [a for a in self.agents if a.name != name] + list(agents)
        return MAWConfig(agents=new_agents, pipeline=new_pipeline)

    def insert_after(self, name: str, agent: MAWAgentConfig) -> MAWConfig:
        if not _has_agent_ref(self.pipeline, name):
            raise ValueError(f"Agent '{name}' not found in pipeline")
        new_node = MAWStepConfig(type="agent", agent_name=agent.name)
        if self.pipeline.type == "agent" and self.pipeline.agent_name == name:
            new_pipeline = MAWStepConfig(
                type="sequential", children=[self.pipeline, new_node]
            )
        else:
            new_pipeline = _insert_after_in_tree(self.pipeline, name, new_node)
        new_agents = list(self.agents) + [agent]
        return MAWConfig(agents=new_agents, pipeline=new_pipeline)

    def remove_agent(self, name: str) -> MAWConfig:
        if not _has_agent_ref(self.pipeline, name):
            raise ValueError(f"Agent '{name}' not found in pipeline")
        new_pipeline = _remove_from_tree(self.pipeline, name)
        if new_pipeline is None:
            raise ValueError("Cannot remove the only agent in the pipeline")
        new_agents = [a for a in self.agents if a.name != name]
        return MAWConfig(agents=new_agents, pipeline=new_pipeline)

    @model_validator(mode="after")
    def _validate_config(self) -> MAWConfig:
        agent_names = {a.name for a in self.agents}

        if len(self.agents) == 1:
            auto_fill_agent_name(self.pipeline, self.agents[0].name)

        # Unique agent names
        if len(agent_names) != len(self.agents):
            seen: set[str] = set()
            for a in self.agents:
                if a.name in seen:
                    raise ValueError(f"Duplicate agent name: '{a.name}'")
                seen.add(a.name)

        # Unique output keys
        output_keys = [a.output_key for a in self.agents]
        if len(set(output_keys)) != len(output_keys):
            seen_keys: set[str] = set()
            for a in self.agents:
                if a.output_key in seen_keys:
                    raise ValueError(f"Duplicate output_key: '{a.output_key}'")
                seen_keys.add(a.output_key)

        validate_node_refs(self.pipeline, agent_names)
        warn_unused_agents(self.pipeline, agent_names)
        warn_terminal_parallel(self.pipeline)

        return self
