"""Render the consolidated private Phase 3 decision report."""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'artifacts/sampo_phase_3'

def main():
 p25=json.loads((ROOT/'artifacts/sampo_phase_2_5/results.json').read_text())['semantic_small_subset']['k_5']
 r=json.loads((OUT/'rerank_results.json').read_text()); all10=r['policies']['all']; trade=r['candidate_tradeoff']
 lines=['# SAMPO Phase 3 decision report','', 'All comparisons use the same fixed 150-example seed-2025 subset. Private GT is evaluation-only. No MAS, 1,000-example Phase 3 LLM pass, or full experiment ran.','', '## Four-condition comparison','', '| Condition | Candidate recall | Overall top-1 | Oracle top-1 | Rescues | Harms | Net | LLM calls | Prompt / completion tokens | Runtime |','| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: |',f"| A. Hybrid lexical (k=5) | {p25['oracle_retrievable_examples']/150:.4f} | {((p25['changed_prediction_analysis']['both_correct_unchanged']+p25['harmed'])/150):.4f} | {p25['lexical_top_1_on_oracle_retrievable']:.4f} | 0 | 0 | 0 | 0 | 0 / 0 | 0 |",f"| B. Hybrid + reranker (k=5) | {p25['oracle_retrievable_examples']/150:.4f} | {p25['overall_top_1']:.4f} | {p25['oracle_retrievable_top_1']:.4f} | {p25['rescued']} | {p25['harmed']} | {p25['net_gain']} | {p25['calls']} | {p25['prompt_tokens']} / {p25['completion_tokens']} | {p25['runtime_seconds']:.1f}s |",f"| C. Candidate-union lexical (k=10) | {all10['retrieval_recall']:.4f} | 0.3000 | 0.4500 | 0 | 0 | 0 | 0 | 0 / 0 | 0 |",f"| D. Candidate-union + reranker (k=10) | {all10['retrieval_recall']:.4f} | {all10['overall_top_1']:.4f} | {all10['oracle_top_1']:.4f} | {all10['rescued']} | {all10['harmed']} | {all10['net_gain']} | {all10['calls']} | {all10['prompt_tokens']} / {all10['completion_tokens']} | n/a |",'', '## Selective candidate-union reranking (k=10)','', '| Policy | LLM fraction | Top-1 | Rescues / harms / net | Net per 100 calls | Tokens per net correction |', '| --- | ---: | ---: | --- | ---: | ---: |']
 for name,x in r['policies'].items():lines.append(f"| {name} | {x['calls']/150:.1%} | {x['overall_top_1']:.4f} | {x['rescued']} / {x['harmed']} / {x['net_gain']} | {x['gain_per_100_calls']:.2f} | {x['tokens_per_net_corrected']:.0f} |")
 lines += ['', '## Candidate-size tradeoff','', '| k | Retrieval recall | End-to-end top-1 | Oracle top-1 | Prompt tokens |','| ---: | ---: | ---: | ---: |']+[f"| {k[2:]} | {x['retrieval_recall']:.4f} | {x['overall_top_1']:.4f} | {x['oracle_top_1']:.4f} | {x['prompt_tokens']} |" for k,x in trade.items()]+['','## Answers','', 'A. Yes. The k=10 candidate union raises candidate recall from 55.3% (hybrid k=5) to 66.7% and union reranking reaches 34.7% versus 31.3% for hybrid reranking.', 'B. Yes. Reranking only retriever-top1 disagreements sends 47.3% of examples, retains the all-policy 34.7% top-1 and +7 net corrections, and cuts calls by 52.7%.', 'C. Yes. Even after the union, 33.3% of examples lack gold at k=10; retrieval remains a dominant error source.', 'D. Label enrichment is not justified before a generated-MAS experiment: the leakage-safe existing-retriever union is already clearly useful (64.5% recall at ~9.9 raw-union candidates).','', '## Decision','', 'Proceed only after user approval: the diagnostic baseline is `candidate union -> retriever-top1 disagreement gate -> selective Luna reranker`. Do not hard-code it into FEDOT.MAS yet.']
 (OUT/'decision_report.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':main()
