"""One generated public-only SAMPO pilot MAS run."""
from __future__ import annotations
import asyncio,json,time,uuid
from pathlib import Path
from fedotmas import MAS
from fedotmas._settings import get_meta_model
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'artifacts/sampo_phase_4_retry'
TASK='''Map each public historical construction work name in the fixed pilot to one of the allowed granular work labels. Maximize top-1 accuracy while using computation efficiently. You have access to public benchmark inputs, several generic candidate retrieval methods, safe persistent prediction storage, and Python/data processing capabilities where available. Use deterministic computation and batching where useful. Semantic LLM reasoning may be used when it is likely to improve decisions, but avoid unnecessary per-example reasoning and avoid moving large datasets through natural-language agent messages. Only public inputs and labels may be used. Private ground truth, historical granular_name, names_mapper, and databases are forbidden. Produce valid top-3 predictions for every pilot example.'''
async def main():
 OUT.mkdir(parents=True,exist_ok=True); run_id='phase4_'+uuid.uuid4().hex; task=TASK+f" Use this fresh prediction-storage run_id exactly: {run_id}. Persist results with the documented prediction sink tools; if a public CSV artifact is produced, import_prediction_file can validate and persist it. Finalize_predictions is required."; mas=MAS(meta_model=get_meta_model(),worker_models=['openai/gpt-5.6-luna','openai/gpt-5-mini'],mcp_servers=['sampo-benchmark','sandbox-light']); config=await mas.generate_config(task);(OUT/'config.json').write_text(config.model_dump_json(indent=2));(OUT/'run_id.txt').write_text(run_id+'\n');(OUT/'model_assignments.json').write_text(json.dumps({'meta_model':get_meta_model(),'workers':{x.name:x.model for x in config.workers}},indent=2));start=time.perf_counter();state=await mas.build_and_run(config,task,timeout=1800);(OUT/'run_state.json').write_text(json.dumps(state,default=str,ensure_ascii=False,indent=2));(OUT/'runtime.json').write_text(json.dumps({'runtime_seconds':time.perf_counter()-start,'prompt_tokens':mas.total_prompt_tokens,'completion_tokens':mas.total_completion_tokens},indent=2))
if __name__=='__main__':asyncio.run(main())
