from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, model_validator

from fedotmas.common.logging import get_logger

_log = get_logger("fedotmas.pipeline.models")


class AgentConfig(BaseModel):
    """Configuration for a single LLM agent."""

    name: str
    instruction: str
    model: str | None = None
    output_key: str
    tools: list[str] = []


class StepConfig(BaseModel):
    """A node in the pipeline tree."""

    type: Literal["agent", "sequential", "parallel", "loop"]

    # For type="agent": reference to an agent config by name.
    agent_name: str | None = None

    # For type="sequential" / "parallel" / "loop": ordered child nodes.
    children: list[StepConfig] = []

    # For type="loop": max iterations before forced exit.
    max_iterations: int | None = None

    @model_validator(mode="before")
    @classmethod
    def _infer_type(cls, data: Any) -> Any:
        """Auto-fill missing ``type`` based on other fields present."""
        if not isinstance(data, dict):
            return data
        if "type" not in data:
            if "agent_name" in data:
                data["type"] = "agent"
            elif "children" in data:
                data["type"] = "sequential"
        return data


class PipelineConfig(BaseModel):
    """Complete pipeline configuration generated by the meta-agent."""

    agents: list[AgentConfig]
    pipeline: StepConfig

    @model_validator(mode="after")
    def _validate_config(self) -> PipelineConfig:
        agent_names = {a.name for a in self.agents}
        output_keys = [a.output_key for a in self.agents]

        # if a single agent exists and a pipeline node of type
        # "agent" is missing agent_name, fill it in automatically.
        if len(self.agents) == 1:
            self._auto_fill_agent_name(self.pipeline, self.agents[0].name)

        # Unique agent names
        if len(agent_names) != len(self.agents):
            seen: set[str] = set()
            for a in self.agents:
                if a.name in seen:
                    raise ValueError(f"Duplicate agent name: '{a.name}'")
                seen.add(a.name)

        # Unique output keys
        if len(set(output_keys)) != len(output_keys):
            seen_keys: set[str] = set()
            for a in self.agents:
                if a.output_key in seen_keys:
                    raise ValueError(f"Duplicate output_key: '{a.output_key}'")
                seen_keys.add(a.output_key)

        # Every agent_name referenced in the tree must exist
        self._validate_node_refs(self.pipeline, agent_names)

        # Warn about agents defined but never referenced
        referenced: set[str] = set()
        self._collect_agent_refs(self.pipeline, referenced)
        unused = agent_names - referenced
        if unused:
            _log.warning("Unused agents: {}", sorted(unused))

        return self

    def _auto_fill_agent_name(self, node: StepConfig, name: str) -> None:
        """Fill missing agent_name when there is exactly one agent."""
        if node.type == "agent" and node.agent_name is None:
            node.agent_name = name
        for child in node.children:
            self._auto_fill_agent_name(child, name)

    def _collect_agent_refs(
        self, node: StepConfig, refs: set[str]
    ) -> None:
        if node.type == "agent" and node.agent_name:
            refs.add(node.agent_name)
        for child in node.children:
            self._collect_agent_refs(child, refs)

    def _validate_node_refs(
        self, node: StepConfig, agent_names: set[str]
    ) -> None:
        if node.type == "agent":
            if node.agent_name is None:
                raise ValueError("Node of type 'agent' must have an agent_name")
            if node.agent_name not in agent_names:
                raise ValueError(
                    f"Pipeline references unknown agent '{node.agent_name}'. "
                    f"Available: {sorted(agent_names)}"
                )
        else:
            if not node.children:
                raise ValueError(
                    f"Node of type '{node.type}' must have at least one child"
                )
            for child in node.children:
                self._validate_node_refs(child, agent_names)
